apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: fil7er-nodejs-ping-pong-db
  serviceName: fil7er-nodejs-ping-pong-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: fil7er-nodejs-ping-pong-db
    spec:
      containers:
      - name: fil7er-nodejs-ping-pong-db
        image: postgres
        ports:
        - containerPort: 5432
          name: postgres-port
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: mysecret
